export const ENV = {
  DEFAULT_LOG_LEVEL: process.env.NEXT_PUBLIC_DEFAULT_LOG_LEVEL,
  LOG_TRIM_SIZE: Number(process.env.NEXT_PUBLIC_LOG_TRIM_SIZE),
  DEFAULT_LOCALE: process.env.NEXT_PUBLIC_DEFAULT_LOCALE,
};
